// STEP 1 (Base): Generate collision-driven observational notes
export const BASE_PREMISE_GENERATION_DEVELOPER_PROMPT = `You are generating observational material.

The goal is to surface diverse, rewriteable, single-sentence collision notes.
A collision occurs when an object, action, or situation is forced to operate under the wrong rule set (misapplied function, wrong tool, wrong standard, wrong purpose).

These are NOT jokes.
Do not write punchlines. Do not "be funny." Do not use joke templates.

METHOD (SILENT)
- Expand context around the topic: objects, actions, tools, processes, settings, substitutes, opposites, and meaning drift.
- Take one hop outward from strong context items to find adjacent, aligned elements that increase rule distance without breaking legibility.
- Generate notes that explicitly state the collision on the page. Do not rely on inference.

ITEM RULES (NON-NEGOTIABLE)
- EXACTLY one sentence per item.
- Each item must express ONE collision or angle.
- Each item must contain at least one concrete object or action.
- Avoid thesis framing, listicles, and "balanced comparison" scaffolds.
- Avoid invented agency/actions that do not arise from the topic. (No "the toast argued," etc.)
- Vary sentence shapes across the set.

OUTPUT FORMAT (STRICT)
Return valid JSON only in exactly this shape:

{
  "items": [
    { "world": "unspecified", "premise": "one sentence collision note" }
  ]
}
`;

// Backward compatibility alias
export const BASE_GENERATION_DEVELOPER_PROMPT_FINAL = BASE_PREMISE_GENERATION_DEVELOPER_PROMPT;

export const REWRITE_DEVELOPER_PROMPT_SNAPSHOT_ESCALATION_FINAL = `You are re-authoring observational material.

The input text is raw material generated by an earlier step.
It represents an observation built around a specific collision
(a mismatch, misapplication, or wrong rule set).

Your task is to re-express this material in a specified voice or style.

IMPORTANT GUIDELINES:

– Ignore the original wording, sentence structure, and phrasing.
– Preserve the underlying collision and the overall sentiment.
– Maintain explicit reference to the key anchor elements that create the collision (the compared items).
  Do not drop either side of the comparison during re-authoring.
– Do not remove, replace, or generalize away the specific element that creates the collision.
  The defining objects or concepts involved in the collision must remain identifiable
  in the re-authored version.
– Do not replace the collision with a different idea.
– Do not reverse or alter the stance of the observation.
– When re-authoring, obey the style contract constraints exactly (e.g., if it forbids concession phrases or question-led openings, do not use them).

You may:
– Substitute words and phrases freely.
– Change sentence structure, rhythm, and length.
– Expand into multiple lines if the voice or style calls for it.
– Introduce supporting language, imagery, or tags that help express
  the same collision more effectively in the given style.

Do not:
– Evaluate the quality of the idea.
– Filter, rank, or judge the material.
– Introduce a new or different collision.
– Add meta commentary or explanation.

OUTPUT FORMAT (STRICT)
Return valid JSON only in exactly this shape:

{
  "jokes": [
    { "world": "<copied from input if provided>", "premise": "<copied from input>", "text": "<re-authored output text>" }
  ]
}

Return the same number of objects as inputs, in the same order.
`;

